<?php
/** Generated by api/generate_admin_hashes.php. Do not commit. */
return [
	'Admin' => '$2y$10$Ju4fiSDLC4ji.1rXRhk9Hu9T.7u19Q8kakY27oRqsn.w413d1MBXu',
	'Adeola' => '$2y$10$B1il1/b087oywhr6oFpA9uVT0XfD3Gst8d3xfroDzOB1jAg/fvga6',
	'Rachael' => '$2y$10$vQ/.IWIMx4hHfSP0XlPkQuNpr.AmiU1pzxev6eUnN3Uyq86TjVUnm',
	'Mayowa' => '$2y$10$u/OlGvsNUkKQjxnwny1q8edjPoro9Xoc0.pVmMvTrPPXPr8SSlScK',
	'Eniola' => '$2y$10$Ww/xvPrd4v6Site1dJjIl.6Pyw48QUHGjeqV/zcrdJRzSrx78Oqxi',
	'Ade' => '$2y$10$2aav/Fj4sGCvV.FcbMwutuGk8dUFbMZT6DOTyhEtL0m9pnboMbD/.',
];
